[[Cards]]
name = "防御"
cost = 1
description = "获得 5(8) 点格挡. "

[[Cards]]
name = "汲取能量"
cost = 1
description = "获得 2(3) 点 EVE 能量. "

[[cards]]
name = "异次元涌动"
cost = 2
description = "获得 4(6) 层 EVE 能量。本回合保持 EVE 能量."
