[[Cards]]
name = "防御"
cost = 1
description = "获得 5(8) 点格挡. "

[[Cards]]
name = "汲取能量"
cost = 1
description = "获得 2(3) 点 EVE 能量. "

[[cards]]
name = "异次元涌动"
cost = 2
description = "获得 4(6) 层 EVE 能量。本回合保持 EVE 能量."

[[cards]]
name = "奇术，轻而易举啊"
cost = 3
description = "造成 15(20) 点伤害，获得 5(7) 层 EVE 能量，打出此牌后，在本回合结束时，失去当前 EVE 层数 ×2 的生命值 "

[[cards]]
name = "逆焰护体"
cost = 1
description = "获得 8(11) 点格挡。【回火】：下回合抽牌数 -1."
